// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TooliRent.Infrastructure.Data;

#nullable disable

namespace TooliRent.Infrastructure.Migrations
{
    [DbContext(typeof(TooliRentDbContext))]
    [Migration("20250917102455_RemoveUserData")]
    partial class RemoveUserData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TooliRent.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("ToolId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ToolId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("TooliRent.Domain.Entities.Tool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RentalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("ToolCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ToolCategoryId");

                    b.ToTable("Tools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Kraftfull borrhammare för betong och tegel.",
                            IsDeleted = false,
                            Name = "Borrhammare",
                            RentalPrice = 250m,
                            Status = 0,
                            ToolCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lättanvänd skruvdragare med två batterier.",
                            IsDeleted = false,
                            Name = "Skruvdragare",
                            RentalPrice = 120m,
                            Status = 1,
                            ToolCategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "En robust såg för alla träprojekt.",
                            IsDeleted = false,
                            Name = "Såg",
                            RentalPrice = 50m,
                            Status = 0,
                            ToolCategoryId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Komplett set med skiftnycklar i olika storlekar.",
                            IsDeleted = false,
                            Name = "Skiftnyckel-set",
                            RentalPrice = 80m,
                            Status = 0,
                            ToolCategoryId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "Effektiv gräsklippare för medelstora trädgårdar.",
                            IsDeleted = false,
                            Name = "Gräsklippare",
                            RentalPrice = 200m,
                            Status = 0,
                            ToolCategoryId = 3
                        },
                        new
                        {
                            Id = 6,
                            Description = "Kraftig lövblås för att snabbt rensa upp i trädgården.",
                            IsDeleted = false,
                            Name = "Lövblås",
                            RentalPrice = 150m,
                            Status = 2,
                            ToolCategoryId = 3
                        });
                });

            modelBuilder.Entity("TooliRent.Domain.Entities.ToolCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ToolCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Verktyg som drivs med el.",
                            Name = "Elverktyg"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Verktyg som används manuellt.",
                            Name = "Handverktyg"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Verktyg för trädgårdsskötsel.",
                            Name = "Trädgårdsverktyg"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Verktyg för målning och renovering.",
                            Name = "Måleriverktyg"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Verktyg för fordon.",
                            Name = "Bilverktyg"
                        });
                });

            modelBuilder.Entity("TooliRent.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TooliRent.Domain.Entities.Booking", b =>
                {
                    b.HasOne("TooliRent.Domain.Entities.Tool", "Tool")
                        .WithMany("Bookings")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TooliRent.Domain.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tool");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TooliRent.Domain.Entities.Tool", b =>
                {
                    b.HasOne("TooliRent.Domain.Entities.ToolCategory", "ToolCategory")
                        .WithMany("Tools")
                        .HasForeignKey("ToolCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToolCategory");
                });

            modelBuilder.Entity("TooliRent.Domain.Entities.Tool", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("TooliRent.Domain.Entities.ToolCategory", b =>
                {
                    b.Navigation("Tools");
                });

            modelBuilder.Entity("TooliRent.Domain.Entities.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
